#!/bin/bash

make clean
make

f2py3 -c --fcompiler=gfortran -lgomp -I source/rnglib.o source/sort.o source/globals.o source/class_line.o source/class_geometry.o source/class_dust.o source/class_obs_data.o source/class_freq_grid.o source/class_grid.o source/electron_scattering.o source/input.o source/init_random_seed.o  source/random_routines.o source/vector_functions.o source/write_out.o source/class_packet.o source/BHmie.o  source/radiative_transfer.o source/model_comparison.o source/driver.o source/bayesian_parameters.o -m damocleslib source/damocles_wrap.f90 